import { EventEmitter } from 'events';
import { ProductionEvent } from '../../types/production.js';

class ProductionEventBus extends EventEmitter {
  emitEvent(event: ProductionEvent) {
    this.emit(event.type, event);
  }
}

export const eventBus = new ProductionEventBus();

export const ProductionEvents = {
  CREATED: 'PRODUCTION_CREATED',
  STARTED: 'PRODUCTION_STARTED',
  BRIEF_CREATED: 'PRODUCTION_BRIEF_CREATED',
  STORYBOARD_CREATED: 'STORYBOARD_CREATED',
  STORYBOARD_UPDATED: 'STORYBOARD_UPDATED',
  STORYBOARD_APPROVAL_REQUIRED: 'STORYBOARD_APPROVAL_REQUIRED',
  STORYBOARD_APPROVED: 'STORYBOARD_APPROVED',
  SCENE_GENERATION_STARTED: 'SCENE_GENERATION_STARTED',
  SCENE_GENERATION_COMPLETED: 'SCENE_GENERATION_COMPLETED',
  ASSEMBLY_STARTED: 'ASSEMBLY_STARTED',
  AUDIO_STARTED: 'AUDIO_STARTED',
  EDITING_STARTED: 'EDITING_STARTED',
  QA_STARTED: 'QA_STARTED',
  QA_PASSED: 'QA_PASSED',
  QA_FAILED: 'QA_FAILED',
  REPAIR_STARTED: 'REPAIR_STARTED',
  COMPLETED: 'PRODUCTION_COMPLETED',
  FAILED: 'PRODUCTION_FAILED',
  CANCELLED: 'PRODUCTION_CANCELLED'
};
